# Generated by Django 2.2.3 on 2019-07-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_blog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='pics/default', upload_to='pics'),
        ),
    ]
