# Generated by Django 2.2.4 on 2019-08-28 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190724_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(default='Board Member', max_length=200)),
                ('name', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='images/profile')),
                ('year', models.DateField(verbose_name='2010')),
            ],
        ),
    ]
