# Generated by Django 2.2.4 on 2019-10-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_sponsor_type_of_sponsor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(verbose_name='date of event')),
                ('time', models.CharField(max_length=8)),
                ('location', models.CharField(max_length=200)),
                ('cover_photo', models.ImageField(upload_to='images/events')),
                ('description', models.TextField(max_length=1000)),
                ('link', models.URLField(max_length=1000)),
                ('current_or_past', models.CharField(choices=[('Current', 'CURRENT'), ('Past', 'PAST')], max_length=250)),
            ],
        ),
    ]
