# Generated by Django 2.2.4 on 2019-10-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_events_portfolio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='title',
            new_name='event_title',
        ),
        migrations.AlterField(
            model_name='events',
            name='current_or_past',
            field=models.CharField(choices=[('CURRENT', 'Current'), ('PAST', 'Past')], max_length=250),
        ),
        migrations.AlterField(
            model_name='events',
            name='portfolio',
            field=models.CharField(choices=[('SOCIAL', 'Social'), ('EDUCATION', 'Education'), ('CAREERS', 'Careers'), ('GENERAL', 'General')], default='GENERAL', max_length=250),
        ),
    ]
