# Generated by Django 2.2.4 on 2019-10-18 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20191018_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='event_title',
            new_name='title',
        ),
    ]
