# Generated by Django 2.2.4 on 2019-10-19 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20191018_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='dummy_field',
        ),
    ]
