# Generated by Django 2.2.4 on 2020-01-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200114_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
